import React from 'react';

export const PAGE_WIDTH_MM = 210;
export const PAGE_HEIGHT_MM = 297;
export const MARGIN_TOP = 10;
export const MARGIN_RIGHT = 10;
export const MARGIN_BOTTOM = 10;
export const MARGIN_LEFT = 10;
export const ATTRIBUTION_TEXT = 'Generated by cvgenerator.zandev.my.id';

export const CONTENT_WIDTH_MM = PAGE_WIDTH_MM - MARGIN_LEFT - MARGIN_RIGHT;
export const CONTENT_HEIGHT_MM = PAGE_HEIGHT_MM - MARGIN_TOP - MARGIN_BOTTOM;

if (
    MARGIN_TOP < 0 ||
    MARGIN_RIGHT < 0 ||
    MARGIN_BOTTOM < 0 ||
    MARGIN_LEFT < 0 ||
    MARGIN_LEFT + MARGIN_RIGHT >= PAGE_WIDTH_MM ||
    MARGIN_TOP + MARGIN_BOTTOM >= PAGE_HEIGHT_MM
) {
    throw new Error('Invalid CV page margins configured in cv-page-layout.ts');
}

const MIN_FOOTER_MARGIN_MM = 6;
if (MARGIN_BOTTOM < MIN_FOOTER_MARGIN_MM) {
    throw new Error(
        `MARGIN_BOTTOM (${MARGIN_BOTTOM}mm) must be at least ${MIN_FOOTER_MARGIN_MM}mm to safely accommodate the CV footer attribution and page numbering without colliding with body content.`,
    );
}

export const pageOuterStyle: React.CSSProperties = {
    width: `${PAGE_WIDTH_MM}mm`,
    height: `${PAGE_HEIGHT_MM}mm`,
    paddingTop: `${MARGIN_TOP}mm`,
    paddingRight: `${MARGIN_RIGHT}mm`,
    paddingBottom: `${MARGIN_BOTTOM}mm`,
    paddingLeft: `${MARGIN_LEFT}mm`,
    boxSizing: 'border-box',
    fontSize: '10pt',
    lineHeight: '1.5',
    backgroundColor: 'white',
    color: '#000',
    boxShadow: '0 0 10px rgba(83, 81, 81, 0.2)',
    margin: '0 auto',
    marginTop: '40px',
    position: 'relative',
    overflowY: 'hidden',
    fontFamily: 'Arial, sans-serif',
};

export const pageContentStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    position: 'relative',
    zIndex: 1,
};

export const printCssString = `
@page {
    size: A4 portrait;
    margin: 0;
}

@media print {
    html, body {
        width: ${PAGE_WIDTH_MM}mm;
        height: ${PAGE_HEIGHT_MM}mm;
        margin: 0;
        padding: 0;
    }
    .cv-margin-guide {
        display: none !important;
    }
}
`;
